In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

# Question 1 
### How likely is it that you roll doubles when rolling two dice?



In [2]:
# expexted 
2/12

0.16666666666666666

In [57]:
# define our variables 
# two dice so two lists 
die_one = [1, 2, 3, 4, 5, 6]
die_two = [1, 2, 3, 4, 5, 6]

# this is a big number so we can test theoretical probability 
die_trials = 100_000

In [58]:
# create an array for each event in this case a die roll
# they each pick a random number one threw six one hundred times
d_one_roll = np.random.choice(die_one, die_trials)
d_two_roll = np.random.choice(die_two, die_trials)

In [59]:
# compare to see how many of the 100 trials match indecating rolling a double 
# this spits out a boolian array of True and False 
# use sum to count the number of instances that are True becuase of the == comparison operator 
(d_two_roll == d_one_roll).sum()

16680

In [60]:
# divide the sum by the total number of trials to get the percentage 
(d_two_roll == d_one_roll).sum() / len(d_one_roll)

# with only 100 trials we can see that the expected value is very close to the actual value

0.1668

In [131]:
# can also use mean 

(d_two_roll == d_one_roll).mean()

# 0.1668

0.1668

# Question 2
### If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?



In [7]:
# expected 
3/8

0.375

In [3]:
# potential coin flip outputs are heads or tails (fair coin)
flip_outcomes = ['H', 'T']
# number of trials is the number of flips, 8
n_trials = 8
n_simulations = 100_000

# the simulation space will be 100k instances of our 8 flip trials
flip_simulations = np.random.choice(flip_outcomes, (n_simulations, n_trials))


In [4]:
flip_simulations[:5,:]


array([['T', 'H', 'T', 'T', 'T', 'T', 'T', 'H'],
       ['T', 'T', 'H', 'T', 'H', 'H', 'H', 'H'],
       ['T', 'T', 'H', 'H', 'T', 'T', 'T', 'T'],
       ['H', 'H', 'T', 'T', 'T', 'T', 'T', 'H'],
       ['H', 'H', 'T', 'T', 'H', 'T', 'T', 'T']], dtype='<U1')

In [150]:
# first set = to 'H' for a boolian mask for the array 
# second sum the all the True values because of the == operator
# therd sum by axis=1 for columns turning it into an array of numbers 
# forth find all instances that = 3 turning it back to boolian vlaues 
# fith sum all of the instances that = True 
exact_three = ((hundred_flips == 'H').sum(axis=1) == 3).sum()

In [151]:
# total of all values that are exacly 3 / total flips 
exact_three / len(hundred_flips)

# or 

((hundred_flips == 'H').sum(axis=1) == 3).mean()

# 0.217

0.21932

In [152]:
# modified the formula to calculate the probabiliy of more than 3 heads
more_than_three = ((hundred_flips == 'H').sum(axis=1) > 3).sum()

In [153]:
# total of all values that are more than 3 / total flips 
more_than_three / len(hundred_flips)

# or 

((hundred_flips == 'H').sum(axis=1) > 3).mean()

### This is not what I expected unless I calculates the expected value wrong 

# 0.6375

0.63648

# Question 3
### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 

### Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?



In [14]:
# expected 
1/4

0.25

In [146]:
# define our variables 

opt = ['web', 'web', 'web', 'data']
cu_trial = ncols = 2 
cu_sim = nrows = 1000

In [154]:
# creates an array with nrows and n cols with 4 choices 

billboards = np.random.choice(opt, (nrows, ncols))

In [17]:
# create an array of bools to get a base understanding if any rows come back True 

billboards == 'data'

array([[False, False],
       [False, False],
       [False,  True],
       ...,
       [ True, False],
       [False, False],
       [False,  True]])

In [18]:
# got a count of all the values that are True 

(billboards == 'data').sum()

529

In [19]:
# sum by axis=1 means that we are adding up all the True's withing every row 
# numbers tell me is there is 1, 2, no 0 True's in a given row 

(billboards == 'data').sum(axis=1)

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 1, 1,
       2, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 2, 1, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 1,
       2, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1,
       0, 1, 0, 2, 0, 2, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 2,
       1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 0, 2,

In [20]:
# set the new array equal to 2 because we only want rows with two True's 
# returns an array of bool values because of the == operator 

(billboards == 'data').sum(axis=1) == 2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,

In [21]:
# here I counted all the rows with two True values giving me the total number of rows 

((billboards == 'data').sum(axis=1) == 2).sum()

68

In [22]:
# created a variable to hold the sum of rows with two True values 

data_billboard = ((billboards == 'data').sum(axis=1) == 2).sum()

In [23]:
# devided the number of rows with two True values with the total number of rows 

data_billboard / len(billboards)

# 068

0.068

# Question 4 

### Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. 

### If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? 

### (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values



In [164]:
# define the values 

pop_trials = 17
pop_sim = 100_000

In [165]:
# we have mean and standard deviation within the np.random.normal function
# use pd.dataframe to make the information tabular and in order to add my number of simulations and days of the trial 
# pandas dataframe need data (np.random.normal), size for number of rows and columns 

pd.DataFrame(np.random.normal(3,1.5, size = (pop_sim, 5)))

0         1         2         3         4
0      2.500011  2.147209  5.652219  2.060233  3.280385
1      1.774162  1.330736  1.609993  3.628218  1.881727
2      4.326445  6.219167  2.395013  2.750595  3.800292
3      2.101692  3.201952  4.699837  1.599973  2.498376
4      1.803430  2.280879  1.815490  2.556299  2.298302
...         ...       ...       ...       ...       ...
99995  2.723913  2.826506  1.945079  2.088096  2.463358
99996  1.295745  2.202109  2.889549  4.711846  3.964435
99997  4.915285  3.354195  3.025072  3.656726  2.414492
99998  1.793283  4.518604  2.784162 -0.074645  4.808703
99999  3.301107  1.134858  0.741575  4.289477  2.128366

[100000 rows x 5 columns]

In [166]:
np.random.normal(3,1.5, size = (pop_sim, 5))

array([[2.39566639, 2.75333732, 2.31324852, 2.18164238, 5.08999979],
       [4.48850424, 0.47782536, 6.13935077, 1.4237205 , 3.30842782],
       [5.74044021, 3.37225581, 1.28953167, 2.79482663, 6.21001178],
       ...,
       [1.91032513, 4.16177296, 3.95279897, 2.55314913, 1.95712209],
       [2.93339833, 3.77468701, 1.98375477, 2.32441756, 4.32332693],
       [5.49714197, 5.13557071, 4.81729552, 3.00470023, 1.69734268]])

In [167]:
# created a variable to hold my dataframe 
sold_pop = pd.DataFrame(np.random.normal(3,1.5, size = (pop_sim, 5)))

In [168]:
# sum every row within the simulation 
sold_pop.sum(axis=1)

0        16.613383
1        12.608046
2        15.232109
3        16.559992
4        19.009064
           ...    
99995    15.392697
99996    12.861073
99997    11.597538
99998    16.710561
99999    13.923845
Length: 100000, dtype: float64

In [169]:
sold_pop.sum(axis=1) < 16

0        False
1         True
2         True
3        False
4        False
         ...  
99995     True
99996     True
99997     True
99998    False
99999     True
Length: 100000, dtype: bool

In [170]:
(sold_pop.sum(axis=1) < 16).mean()

0.61698

# Question 5

### Men have an average height of 178 cm and standard deviation of 8cm.
### Women have a mean of 170, sd = 6cm.
### Since you have means and standard deviations, you can use np.random.normal to generate observations.
### If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [172]:
hight_sim = 100_000
men_hight = np.random.normal(178, 8, hight_sim)
woman_hight = np.random.normal(170, 6, hight_sim)

In [173]:
(woman_hight > men_hight).sum()
(woman_hight > men_hight).sum() / len(woman_hight)

# or 

(woman_hight > men_hight).mean()

0.21062

# Question 6 

### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 

### What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?



In [5]:
# lets calculate our event space:
prob_event_fails = 1/250
n_trials = 50 #(number of students installing in this classroom)
install_simulations = np.random.random((n_simulations, n_trials))

In [6]:
# way b:
outcomes = ['successful_install', 'failed_install']
install_simulations_choice = np.random.choice(
    outcomes,
    size=(n_simulations, n_trials),
    p=((1-(1/250), (1/250))))

In [7]:
# run the rest of the problem with method a:
# compare our installs with our corrupted install threshold
(install_simulations < prob_event_fails)

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [8]:
# across everything in each simulation, if all 50 are False, (0), then I had all clean installs
((install_simulations < prob_event_fails).sum(axis=1) == 0).mean()

0.81942

In [191]:
# for 100 students 

install_trial_two = 100
install_for_one_hundred = np.random.random((install_sim, install_trial_two))
((install_for_one_hundred < prob_issue).sum(axis=1) > 1).mean()

0.06195

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?



In [9]:
prob_event_fails = 1/250
n_trials = 150 #(number of students installing in this classroom)
install_simulations = np.random.random((n_simulations, n_trials))
# this time, see how many we have succesful across 150 students
# the average of at least one failed install (over 0)
((install_simulations < prob_event_fails).sum(axis=1) > 0).mean()

0.45059

### How likely is it that 450 students all download anaconda without an issue?



In [10]:
prob_event_fails = 1/250
n_trials = 450 #(number of students installing in this classroom)
install_simulations = np.random.random((n_simulations, n_trials))
# this time, see how many we have succesful across 150 students
# the average of at least one failed install (over 0)
((install_simulations < prob_event_fails).sum(axis=1) == 0).mean()

0.16523

In [88]:
no_issue = np.random.random((install_sim, install_trial_four))
students_no_issue = no_issue < prob_issue
clean_install = (students_no_issue.sum(axis=1) == 0).sum()
clean_install / len(students_no_issue)

0.177

# Question 7

### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 

### However, you haven't seen a food truck there in 3 days. How unlikely is this?



In [99]:
prob_no_show = .7
n_days = 3
n_sim = 100_000

In [192]:
food_truck = np.random.random((n_sim, n_days))
no_show = ((food_truck < prob_no_show).sum(axis=1) == 0).mean()
no_show 

0.02738

### How likely is it that a food truck will show up sometime this week?



In [109]:
prob_no_show = .7
n_days_cont = 7
n_sim = 100_000

food_truck = np.random.random((n_sim, n_days_cont))
will_show = ((food_truck >= prob_no_show).sum(axis=1) >= 1).mean()
no_show 

0.34095

In [ ]:
outcomes = ['truck', 'no_lunch']
# trials are three days
truck_simulations = np.random.choice(outcomes, 
                 size=(n_simulations, 3),
                 p=(0.7, 0.3))

# Question 8 

### If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?



In [ ]:
1/3

In [12]:
# lets simulate 40 birthdays!
# so lets create a selection based on a range of values, since there are 365
# possible birthday choices for each person and we want them to be specific values
n_trials = 23
birthday_sims = np.random.choice(range(365),size=(n_simulations, n_trials))

In [14]:
birthday_sims

array([[271, 160, 183, ...,  97,  92, 159],
       [302,  81, 179, ..., 235, 303,  85],
       [ 99, 136, 237, ..., 207,  61, 217],
       ...,
       [159,  12, 104, ..., 237,  73, 222],
       [120, 216, 271, ..., 218,  63,  73],
       [258, 346, 184, ..., 294, 196, 313]])

In [16]:
birthday_df = pd.DataFrame(birthday_sims)
birthday_df.sample(3)

0    1    2    3    4    5   6    7    8    9   ...   13   14   15  \
73709  341   97   46  248  299   42  54  161   80  340  ...   69   47  221   
67933  110  125   39   81  217  150  70   67  243  102  ...  275  177   53   
99196  118  292  156  338  279  153  24  290  254  106  ...  228   94  354   

        16   17  18   19   20   21   22  
73709   37  205  82  176  344  226   73  
67933   61  209  15  346  265  256  148  
99196  280  329  79   41   54  126   58  

[3 rows x 23 columns]

In [19]:
(birthday_df.nunique(axis=1) < 23).mean()

0.51057

In [20]:
n_trials = 20
birthday_sims = np.random.choice(range(365),size=(n_simulations, n_trials))
birthday_df = pd.DataFrame(birthday_sims)
(birthday_df.nunique(axis=1) < n_trials).mean()

0.41095

In [21]:
n_trials = 40
birthday_sims = np.random.choice(range(365),size=(n_simulations, n_trials))
birthday_df = pd.DataFrame(birthday_sims)
(birthday_df.nunique(axis=1) < n_trials).mean()

0.89365